### PR TITLE
feat: check for the 'find' permissions in the router controller

### PR DESCRIPTION
**Pull request by boazpoolman**

### CODE REVIEW

**Comment by Alexnortung** [comment]
I haven't tested it, but I am curious why the sanitize output and transform response is not enough?

**Comment by boazpoolman** [comment]
Sadly it's not.

The transform function will simply transform, and the sanitize function will only sanitize the fields. Not the entire entity.

This PR will handle just that. Throwing a 403 if you lack permissions.

**Comment by boazpoolman** [comment]
@Alexnortung I've written some tests for the /router endpoint.

Currently it fails as the API returns a 200 for a page which you are not allowed to see.
See the test results: https://github.com/pluginpal/strapi-webtools/actions/runs/7708380471/job/21007376133#step:8:41

Those tests should be passing as soon as this PR gets merged.

**Review by Alexnortung — APPROVED** [review]
I was thinking that a policy might be better for checking the persmissions, rather than to check permissions during the controller function. 

However since we only have one controller function I think this is fine, since adding a policy would also mean that we should call the `byPath` function twice (in the policy and in the controller).

I have also tested and it works as expected.

**Pull request merged**
