### PR TITLE
fix(urlAliasService): Use the duplicate checked url path

### PR DESCRIPTION
**Pull request by Alexnortung**
### What does it do?

Prior to this commit, the duplicate check was run, but the new url path was not used.
This commit also refactors the duplicateCheck function to a separate function without side effects.

### Why is it needed?

The duplicate check needs to run and use the new url path

### CODE REVIEW

**Review by boazpoolman — APPROVED** [review]
Haven't tested it, but LGTM.

I'll make sure to test it before merging.

**Comment by boazpoolman** [comment]
This fix seems to work!

Though I am seeing some other issue with the duplicateCheck function.
Not sure what's happening, but after publishing/unpublishing a few times I end up with a URL alias like `/en/test/2-2-0`.

**Comment by Alexnortung** [comment]
Interesting, what is actually happening when a content type is published/unpublished? Is the update decorator called?

**Comment by boazpoolman** [comment]
Exactly. The update decorator is called.

Though it might be related to #113

**Comment by Alexnortung** [comment]
Ohhhh, I see, I was actually just trying to fix this and it was almost exactly the same fix as in #113, I will be sure to suggest my changes to #113 :)

**Pull request merged**
