### PR TITLE
chore(types): Added types for plugin options and removed ts-ignore

### PR DESCRIPTION
**Pull request by Alexnortung**
### What does it do?

Added plugin options type so that we do not need to use `@ts-ignore`

I also tried fixing some eslint errors, but I am still getting some and it seems like eslint cannot infer the type correctly, maybe a new version is needed @boazpoolman 

### Why is it needed?

We should avoid using `@ts-ignore` when it is possible

### CODE REVIEW

**Comment by Alexnortung** [comment]
I think the problem here is eslint, if you hover over the values in your editor you will see that the types are not `any` as eslint says. So I think at least the `@typescript-eslint/parser` needs to be updated, but that also means all the eslint plugins should probably be updated too. The eslint dependencies is not defined in this project, so I am not quite sure how to update all of them.

**Comment by boazpoolman** [comment]
I see. The issues are rather eslint instead of hard Typescript errors.
But then still; this is not an issue in the head `monorepo` branch. Meaning that something in this PR is causing these linting warning to occur.

**Comment by Alexnortung** [comment]
Yes, you're right, the errors only occur when the `declare module` part in the `strapi.ts` file is there.

**Comment by boazpoolman** [comment]
I suspect it has something to do with the location of the `/types/generated` files.
Those are generated **and** read by `@strapi/strapi` to strictly type it's return types.
For example the response of `strapi.entityService` is modified like that.
Those files are just magically picked up by `@strapi/strapi` as it expects it to be in the `/types/generated` location.

Maby if we move the `declare module @strapi/strapi` we also need to move that types folder to reflect that change?

That's the only thing I can think of.

**Comment by Alexnortung** [comment]
I don't think strapi expects the typing files to be anywhere, I think it is entirely up to what we set in the `typeroots` or `include`  in the tsconfig file.

The way that we override Schema in this PR seems to be correct since typescript does pick up the correct types, however it is only eslint that fails to get the types right. I did find some issues on some eslint repos about similar issues, so it might not be possible to fix right now.

I tried to install newer versions of the typescript eslint parser and the plugins, but it did not make any difference.

**Comment by boazpoolman** [comment]
I think we may just have to resort to using `@ts-ignore` and `as boolean`. It's not ideal, but extending the `@strapi/strapi` types like this just gives to much issues. Let's hope the `PluginOptions` will just be properly typed by strapi one day.

**Comment by Alexnortung** [comment]
Yeah, you are probably right and we don't know how long it takes for a fix to be release for eslint.

However Imo I think it would be better to use `@ts-expect-error` instead of `@ts-ignore` so that when the types work one day, we can easily remove all the `@ts-expect-error`s :)

**Comment by boazpoolman** [comment]
Fine by me!

**Comment by boazpoolman** [comment]
Just took another jab at making this work but was unable to.

I'll close this PR in favor of #91

**Pull request closed without merging**
