### PR TITLE
feat: adding spanish and turkish translations

### PR DESCRIPTION
**Pull request by SalahAdDin**
### What does it do?
It adds Spanish and Turkish translations for Core and Sitemap addon.

### Why is it needed?

Spanish and Turkish speakers will require this.

### How to test it?

Manually on the admin.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/pull request

### CODE REVIEW

**Review by boazpoolman — CHANGES_REQUESTED** [review]
Hey @SalahAdDin,

Can you add a changeset for both the packages you’ve changed?
That’ll schedule them for deploy.

**Comment by SalahAdDin** [comment]
@boazpoolman how can I do that?

**Comment by boazpoolman** [comment]
https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md

**Review by boazpoolman — CHANGES_REQUESTED** [review]
For the core package, you must register the new translations manually.
You can do that here: https://github.com/pluginpal/strapi-webtools/blob/d683cd5ab265433e2e81118ddd28629657c23270/packages/core/admin/index.ts#L95

Afterwards we’re ready to get this merged!

**Comment by SalahAdDin** [comment]
> For the core package, you must register the new translations manually. You can do that here:
> 
> https://github.com/pluginpal/strapi-webtools/blob/d683cd5ab265433e2e81118ddd28629657c23270/packages/core/admin/index.ts#L95
> 
> Afterwards we’re ready to get this merged!

Done!

**Comment by SalahAdDin** [comment]
@boazpoolman Why are the tests failing?

**Comment by boazpoolman** [comment]
Seems to be because of inability to upload the coverage files to codecov

**Comment by SalahAdDin** [comment]
> Seems to be because of the inability to upload the coverage files to codecov

how can I fix it?

**Comment by boazpoolman** [comment]
Nothing you can do about it. We need to add an authentication key to make it work again.

**Review by boazpoolman — APPROVED** [review]

**Comment by SalahAdDin** [comment]
Finally!

**Pull request merged**
