### PR TITLE
feat: Setup queue API

### PR DESCRIPTION
**Pull request by boazpoolman**
### Queue documentation

To solve #14 we need queueing. This PR is a setup for a queue system. Here some docs:

**Create queue**
To create a queue you have to call the `create` service which takes one parameter that is a string that is unique to your queue. We refer to this as the name of the queue.

```
const { getPluginService } = require('./util/getPluginService');

getPluginService('queueService').create("my queue");
```

**Add jobs**
Once you have created your queue you have to add jobs to it. You can do that by calling the `addJob` service which takes two parameters. The first being the name of the queue, and the second being the data of the job.

```
await getPluginService('queueService').addJob("my queue", {
  some: 'data',
});
await getPluginService('queueService').addJob("my queue", {
  some: 'more data',
});
await getPluginService('queueService').addJob("my queue", {
  some: 'even data',
});
```

**Process queue**
After creating your queue and adding your jobs you have to process the queue. You can do that by calling the `process` service which takes two parameters. The first being the name of the queue, the second is a function that will be called to process a single job.

```
await getPluginService('queueService').process("my queue", async (job, done) => {
  // job.data is the job data.
  console.log('we be processing the job breh', job.data);

  // Call the done function when you're done processing the job.
  done();
});
```

### CODE REVIEW

**Comment by Alexnortung** [comment]
Hey Boaz, I think it is a good idea to implement a queue, I am also maintaining another plugin which could also use a queue, maybe we could make a separate queue plugin which this and other plugins could use?

**Comment by boazpoolman** [comment]
Yeah, that crossed my mind too. I'm all for it!

**Comment by SalahAdDin** [comment]
> Yeah, that crossed my mind too. I'm all for it!

not finished yet?

**Comment by boazpoolman** [comment]
Sadly I haven't found the time to continue this feature.

I think its still something that could be very helpful for the Strapi ecosystem.

**Comment by SalahAdDin** [comment]
> Sadly I haven't found the time to continue this feature.
> 
> I think its still something that could be very helpful for the Strapi ecosystem.

Maybe asking for some help on Discord...

**Comment by boazpoolman** [comment]
Would you like to take the lead on this project?

I got my hands full working on the core features of Webrools.

**Comment by SalahAdDin** [comment]
@boazpoolman is #14 related to this issue: https://github.com/pluginpal/strapi-webtools/issues/150?

**Pull request closed without merging**
