### PR TITLE
fix: filter out unpublished pages from the router endpoint

### PR DESCRIPTION
**Pull request by boazpoolman**

### CODE REVIEW

**Review by Alexnortung — COMMENTED** [review]
I'm not really convinced this is the desired behavior. For example if i fetch `/api/tests` I should not get any draft entries, but if `test` with id `4` is a draft and I fetch that `/api/tests/4` strapi will return that entry even though it is still a draft.

For consistency I think we should not filter out drafts by default for the `/webtools/router` endpoint.

**Comment by boazpoolman** [comment]
Hmm. Interesting take on the matter.

I like your idea of consistency. Though on the other hand it would make sense to me that an 'unpublished' page would not be accessible on my website, and thus not returned from the router.

**Comment by Alexnortung** [comment]
Well you are still able to set the `publicationState=live` in the query in the fetch that your website is making.
For example if you are fetching a `post` content type by it's id, then you would probably also set `publicationState=live` when you fetch it. And I think some users may find it confusing if they don't get draft entries from url alias, but they do get the draft from other content types.

I do agree that it is more intuitive that draft entries are not fetched by default, but this is not the case for Strapi. So again I would argue that consistency is more important than what individual plugin maintainers want.

**Comment by boazpoolman** [comment]
Allright. Fair point. Let's keep it this way.

**Pull request closed without merging**
