### PR TITLE
fix: duplicateCheck will use an ignore id

### PR DESCRIPTION
**Pull request by Alexnortung**
### What does it do?

The duplicateCheck function should ignore itself when checking duplicates.

### Related issue(s)/PR(s)

Fixes bug from #115

### CODE REVIEW

**Review by boazpoolman — APPROVED** [review]
LGTM.

We really need some tests for the URL alias creation and pattern resolving.

**Comment by Alexnortung** [comment]
I have modified the test setup a bit. While running the tests, it shouldn't need to listen on any ports nor any sockets. The database connection will be closed before destroying strapi.

I have also added a test for the case that I solved in this PR. I also checked that the test failed previous to this PR.

**Comment by Alexnortung** [comment]
Hmm, codecov is reading the `helper.js` file. Should I delete the unused function? @boazpoolman

**Review by boazpoolman — APPROVED** [review]

**Comment by boazpoolman** [comment]
No, you don't have to delete the helper functions. They're not part of the plugin and therfor shouldn't even be checked by codecov.

Maby we have to configure codecov to only check files in the `/packages` folder. That would probably bump the coverage percentage as well.

**Pull request merged**
